CREATE TABLE BUILTIN_USERS (
  ID INT NOT NULL,
  USERNAME VARCHAR(255),
  PASSWORD VARCHAR(255),
  ROLE VARCHAR(255)
);

ALTER TABLE BUILTIN_USERS ADD PRIMARY KEY (ID);

INSERT INTO BUILTIN_USERS (ID, USERNAME, PASSWORD, ROLE) VALUES (1, 'admin', 'admin', 'platinum');
INSERT INTO BUILTIN_USERS (ID, USERNAME, PASSWORD, ROLE) VALUES (2, 'sheldon', 'sheldon', 'gold');
INSERT INTO BUILTIN_USERS (ID, USERNAME, PASSWORD, ROLE) VALUES (3, 'penny', 'penny', 'silver');