CREATE TABLE JOB (
    ID BIGINT NOT NULL,
    VERSION BIGINT NOT NULL,
    OWNER VARCHAR(255),
    TYPE VARCHAR(255),
    CREATIONDATE BIGINT NOT NULL,
    DUEDATE BIGINT NOT NULL,
    STARTDATE BIGINT NOT NULL,
    STOPDATE BIGINT NOT NULL,
    STATUS VARCHAR(255),
    PROGRESSION BIGINT NOT NULL,
    MESSAGE CLOB
);

CREATE TABLE JOB_PARAMS (
    JOB_ID BIGINT NOT NULL,
    PARAMS VARCHAR(255),
    PARAMS_KEY VARCHAR(255) NOT NULL
);

ALTER TABLE JOB	ADD PRIMARY KEY (ID);

ALTER TABLE JOB_PARAMS ADD PRIMARY KEY (JOB_ID, PARAMS_KEY);
